name: My Action
on:
  workflow_dispatch:
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: My Action
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer {{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/myniceyorg/another-repo/pages \
          -d '{"source":{"branch":"main","path":"/"}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
