name: Create a Dummy Commit

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  CommitChange:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: check
        with:
          require: 'write'
          check-contributor: true

      - run: echo "user-permission = ${{ steps.check.outputs.user-permission }}"
      - run: echo "require-result = ${{ steps.check.outputs.require-result }}"
      - run: echo "check-result = ${{ steps.check.outputs.check-result }}"cks if the actor has read access, and if so, creates a dummy commit.





