name: Create a Dummy Commit

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  CommitChange:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Dummy Commit
        uses: actions-cool/create-dummy-commit@v1
        id: create
        with:
          message: '${{{name}}} is a great person'
          branch: 'main'


