name: Create a Dummy Commit

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  CommitChange:
    runs-on: ubuntu-latest
    steps:
      - name: Check User Permissions
        uses: actions-cool/check-user-permission@v2
        id: check
        with:
          require: 'write'
          check-contributor: true

      # Creates a dummy commit if the user has write permissions

      run: |
        echo "Hello ${{{name}}}, from ${{{home}}}"
        git commit -m "Hello ${{{name}}}, from ${{{home}}}"
        git push
        echo "Done"

