name: Create a Dummy Commit

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  CommitChange:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Ali Kalout'
          git config --global user.email 'Ali-Kalout@users.noreply.github.com'
          git add report.txt
          git commit -m "Automated report"
          git push


